---
- name: add neo4j apt-key
  apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key
    state: present
- name: add neo4j repository
  apt_repository:
    repo: deb https://debian.neo4j.org/repo stable/
    state: present
    update_cache: yes
- name: install neo4j
  apt:
    name: neo4j
    state: present
- name: Enable service neo4j
  service:
    name: neo4j
    enabled: yes

- name: Uncomment default listen address
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#\s*dbms.connectors.default_listen_address*$'
    line: 'dbms.connectors.default_listen_address=0.0.0.0'
- name: Uncomment bolt connector listen address
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#\s*dbms.connectors.bolt.listen_address*$'
    line: 'dbms.connectors.bolt.listen_address=:7687'
- name: Uncomment http listen address
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#\s*dbms.connectors.http.listen_address*$'
    line: 'dbms.connectors.http.listen_address=:7474'
- name: Uncomment https listen address
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#\s*dbms.connectors.https.listen_address*$'
    line: 'dbms.connectors.https.listen_address=:7473'
- name: Uncomment web authentication
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#\s*dbms.security.auth_enabled*$'
    line: 'dbms.security.auth_enabled=false'
  notify:
    - restart neo4j