---
- name: install apt packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - aptitude
    - build-essential
    - git-core
    - jq
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - ntp
    - python-pip
    - python3
    - python3-apt
    - python3-dev
    - python3-pip
    - zlib1g-dev
    - zip
